// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type StringMsg struct {
	Val                  string   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMsg) Reset()         { *m = StringMsg{} }
func (m *StringMsg) String() string { return proto.CompactTextString(m) }
func (*StringMsg) ProtoMessage()    {}
func (*StringMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *StringMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMsg.Unmarshal(m, b)
}
func (m *StringMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMsg.Marshal(b, m, deterministic)
}
func (m *StringMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMsg.Merge(m, src)
}
func (m *StringMsg) XXX_Size() int {
	return xxx_messageInfo_StringMsg.Size(m)
}
func (m *StringMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StringMsg proto.InternalMessageInfo

func (m *StringMsg) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

// This is how we get polymorphic behavior for ProfileControls
type ProfileControl struct {
	// Types that are valid to be assigned to Sub:
	//	*ProfileControl_Group
	//	*ProfileControl_Enum
	//	*ProfileControl_Intensity
	//	*ProfileControl_PanTilt
	//	*ProfileControl_LedVar
	Sub                  isProfileControl_Sub `protobuf_oneof:"sub"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProfileControl) Reset()         { *m = ProfileControl{} }
func (m *ProfileControl) String() string { return proto.CompactTextString(m) }
func (*ProfileControl) ProtoMessage()    {}
func (*ProfileControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ProfileControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileControl.Unmarshal(m, b)
}
func (m *ProfileControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileControl.Marshal(b, m, deterministic)
}
func (m *ProfileControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileControl.Merge(m, src)
}
func (m *ProfileControl) XXX_Size() int {
	return xxx_messageInfo_ProfileControl.Size(m)
}
func (m *ProfileControl) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileControl.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileControl proto.InternalMessageInfo

type isProfileControl_Sub interface {
	isProfileControl_Sub()
}

type ProfileControl_Group struct {
	Group *GroupProfileControl `protobuf:"bytes,1,opt,name=group,proto3,oneof"`
}

type ProfileControl_Enum struct {
	Enum *EnumProfileControl `protobuf:"bytes,2,opt,name=enum,proto3,oneof"`
}

type ProfileControl_Intensity struct {
	Intensity *IntensityProfileControl `protobuf:"bytes,3,opt,name=intensity,proto3,oneof"`
}

type ProfileControl_PanTilt struct {
	PanTilt *PanTiltProfileControl `protobuf:"bytes,4,opt,name=panTilt,proto3,oneof"`
}

type ProfileControl_LedVar struct {
	LedVar *LedVarProfileControl `protobuf:"bytes,5,opt,name=ledVar,proto3,oneof"`
}

func (*ProfileControl_Group) isProfileControl_Sub() {}

func (*ProfileControl_Enum) isProfileControl_Sub() {}

func (*ProfileControl_Intensity) isProfileControl_Sub() {}

func (*ProfileControl_PanTilt) isProfileControl_Sub() {}

func (*ProfileControl_LedVar) isProfileControl_Sub() {}

func (m *ProfileControl) GetSub() isProfileControl_Sub {
	if m != nil {
		return m.Sub
	}
	return nil
}

func (m *ProfileControl) GetGroup() *GroupProfileControl {
	if x, ok := m.GetSub().(*ProfileControl_Group); ok {
		return x.Group
	}
	return nil
}

func (m *ProfileControl) GetEnum() *EnumProfileControl {
	if x, ok := m.GetSub().(*ProfileControl_Enum); ok {
		return x.Enum
	}
	return nil
}

func (m *ProfileControl) GetIntensity() *IntensityProfileControl {
	if x, ok := m.GetSub().(*ProfileControl_Intensity); ok {
		return x.Intensity
	}
	return nil
}

func (m *ProfileControl) GetPanTilt() *PanTiltProfileControl {
	if x, ok := m.GetSub().(*ProfileControl_PanTilt); ok {
		return x.PanTilt
	}
	return nil
}

func (m *ProfileControl) GetLedVar() *LedVarProfileControl {
	if x, ok := m.GetSub().(*ProfileControl_LedVar); ok {
		return x.LedVar
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProfileControl) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProfileControl_Group)(nil),
		(*ProfileControl_Enum)(nil),
		(*ProfileControl_Intensity)(nil),
		(*ProfileControl_PanTilt)(nil),
		(*ProfileControl_LedVar)(nil),
	}
}

type GroupProfileControl struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Controls             []*ProfileControl `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GroupProfileControl) Reset()         { *m = GroupProfileControl{} }
func (m *GroupProfileControl) String() string { return proto.CompactTextString(m) }
func (*GroupProfileControl) ProtoMessage()    {}
func (*GroupProfileControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GroupProfileControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupProfileControl.Unmarshal(m, b)
}
func (m *GroupProfileControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupProfileControl.Marshal(b, m, deterministic)
}
func (m *GroupProfileControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupProfileControl.Merge(m, src)
}
func (m *GroupProfileControl) XXX_Size() int {
	return xxx_messageInfo_GroupProfileControl.Size(m)
}
func (m *GroupProfileControl) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupProfileControl.DiscardUnknown(m)
}

var xxx_messageInfo_GroupProfileControl proto.InternalMessageInfo

func (m *GroupProfileControl) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupProfileControl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupProfileControl) GetControls() []*ProfileControl {
	if m != nil {
		return m.Controls
	}
	return nil
}

type EnumProfileControlOption struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []int32  `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	VarName              string   `protobuf:"bytes,3,opt,name=varName,proto3" json:"varName,omitempty"`
	VarOffset            int32    `protobuf:"varint,4,opt,name=varOffset,proto3" json:"varOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumProfileControlOption) Reset()         { *m = EnumProfileControlOption{} }
func (m *EnumProfileControlOption) String() string { return proto.CompactTextString(m) }
func (*EnumProfileControlOption) ProtoMessage()    {}
func (*EnumProfileControlOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *EnumProfileControlOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumProfileControlOption.Unmarshal(m, b)
}
func (m *EnumProfileControlOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumProfileControlOption.Marshal(b, m, deterministic)
}
func (m *EnumProfileControlOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumProfileControlOption.Merge(m, src)
}
func (m *EnumProfileControlOption) XXX_Size() int {
	return xxx_messageInfo_EnumProfileControlOption.Size(m)
}
func (m *EnumProfileControlOption) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumProfileControlOption.DiscardUnknown(m)
}

var xxx_messageInfo_EnumProfileControlOption proto.InternalMessageInfo

func (m *EnumProfileControlOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnumProfileControlOption) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *EnumProfileControlOption) GetVarName() string {
	if m != nil {
		return m.VarName
	}
	return ""
}

func (m *EnumProfileControlOption) GetVarOffset() int32 {
	if m != nil {
		return m.VarOffset
	}
	return 0
}

type EnumProfileControl struct {
	Id                   string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChannelIx            int32                       `protobuf:"varint,3,opt,name=channelIx,proto3" json:"channelIx,omitempty"`
	Options              []*EnumProfileControlOption `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *EnumProfileControl) Reset()         { *m = EnumProfileControl{} }
func (m *EnumProfileControl) String() string { return proto.CompactTextString(m) }
func (*EnumProfileControl) ProtoMessage()    {}
func (*EnumProfileControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *EnumProfileControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumProfileControl.Unmarshal(m, b)
}
func (m *EnumProfileControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumProfileControl.Marshal(b, m, deterministic)
}
func (m *EnumProfileControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumProfileControl.Merge(m, src)
}
func (m *EnumProfileControl) XXX_Size() int {
	return xxx_messageInfo_EnumProfileControl.Size(m)
}
func (m *EnumProfileControl) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumProfileControl.DiscardUnknown(m)
}

var xxx_messageInfo_EnumProfileControl proto.InternalMessageInfo

func (m *EnumProfileControl) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EnumProfileControl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnumProfileControl) GetChannelIx() int32 {
	if m != nil {
		return m.ChannelIx
	}
	return 0
}

func (m *EnumProfileControl) GetOptions() []*EnumProfileControlOption {
	if m != nil {
		return m.Options
	}
	return nil
}

type IntensityProfileControl struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChannelIx            int32    `protobuf:"varint,3,opt,name=channelIx,proto3" json:"channelIx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntensityProfileControl) Reset()         { *m = IntensityProfileControl{} }
func (m *IntensityProfileControl) String() string { return proto.CompactTextString(m) }
func (*IntensityProfileControl) ProtoMessage()    {}
func (*IntensityProfileControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *IntensityProfileControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntensityProfileControl.Unmarshal(m, b)
}
func (m *IntensityProfileControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntensityProfileControl.Marshal(b, m, deterministic)
}
func (m *IntensityProfileControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntensityProfileControl.Merge(m, src)
}
func (m *IntensityProfileControl) XXX_Size() int {
	return xxx_messageInfo_IntensityProfileControl.Size(m)
}
func (m *IntensityProfileControl) XXX_DiscardUnknown() {
	xxx_messageInfo_IntensityProfileControl.DiscardUnknown(m)
}

var xxx_messageInfo_IntensityProfileControl proto.InternalMessageInfo

func (m *IntensityProfileControl) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IntensityProfileControl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IntensityProfileControl) GetChannelIx() int32 {
	if m != nil {
		return m.ChannelIx
	}
	return 0
}

type PanTiltProfileControlAxis struct {
	Coarse               int32    `protobuf:"varint,1,opt,name=coarse,proto3" json:"coarse,omitempty"`
	Fine                 int32    `protobuf:"varint,2,opt,name=fine,proto3" json:"fine,omitempty"`
	MinRad               float64  `protobuf:"fixed64,3,opt,name=minRad,proto3" json:"minRad,omitempty"`
	MaxRad               float64  `protobuf:"fixed64,4,opt,name=maxRad,proto3" json:"maxRad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PanTiltProfileControlAxis) Reset()         { *m = PanTiltProfileControlAxis{} }
func (m *PanTiltProfileControlAxis) String() string { return proto.CompactTextString(m) }
func (*PanTiltProfileControlAxis) ProtoMessage()    {}
func (*PanTiltProfileControlAxis) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *PanTiltProfileControlAxis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PanTiltProfileControlAxis.Unmarshal(m, b)
}
func (m *PanTiltProfileControlAxis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PanTiltProfileControlAxis.Marshal(b, m, deterministic)
}
func (m *PanTiltProfileControlAxis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PanTiltProfileControlAxis.Merge(m, src)
}
func (m *PanTiltProfileControlAxis) XXX_Size() int {
	return xxx_messageInfo_PanTiltProfileControlAxis.Size(m)
}
func (m *PanTiltProfileControlAxis) XXX_DiscardUnknown() {
	xxx_messageInfo_PanTiltProfileControlAxis.DiscardUnknown(m)
}

var xxx_messageInfo_PanTiltProfileControlAxis proto.InternalMessageInfo

func (m *PanTiltProfileControlAxis) GetCoarse() int32 {
	if m != nil {
		return m.Coarse
	}
	return 0
}

func (m *PanTiltProfileControlAxis) GetFine() int32 {
	if m != nil {
		return m.Fine
	}
	return 0
}

func (m *PanTiltProfileControlAxis) GetMinRad() float64 {
	if m != nil {
		return m.MinRad
	}
	return 0
}

func (m *PanTiltProfileControlAxis) GetMaxRad() float64 {
	if m != nil {
		return m.MaxRad
	}
	return 0
}

type PanTiltProfileControl struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pan                  *PanTiltProfileControlAxis `protobuf:"bytes,3,opt,name=pan,proto3" json:"pan,omitempty"`
	Tilt                 *PanTiltProfileControlAxis `protobuf:"bytes,4,opt,name=tilt,proto3" json:"tilt,omitempty"`
	ChSpeed              int32                      `protobuf:"varint,5,opt,name=chSpeed,proto3" json:"chSpeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PanTiltProfileControl) Reset()         { *m = PanTiltProfileControl{} }
func (m *PanTiltProfileControl) String() string { return proto.CompactTextString(m) }
func (*PanTiltProfileControl) ProtoMessage()    {}
func (*PanTiltProfileControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *PanTiltProfileControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PanTiltProfileControl.Unmarshal(m, b)
}
func (m *PanTiltProfileControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PanTiltProfileControl.Marshal(b, m, deterministic)
}
func (m *PanTiltProfileControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PanTiltProfileControl.Merge(m, src)
}
func (m *PanTiltProfileControl) XXX_Size() int {
	return xxx_messageInfo_PanTiltProfileControl.Size(m)
}
func (m *PanTiltProfileControl) XXX_DiscardUnknown() {
	xxx_messageInfo_PanTiltProfileControl.DiscardUnknown(m)
}

var xxx_messageInfo_PanTiltProfileControl proto.InternalMessageInfo

func (m *PanTiltProfileControl) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PanTiltProfileControl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PanTiltProfileControl) GetPan() *PanTiltProfileControlAxis {
	if m != nil {
		return m.Pan
	}
	return nil
}

func (m *PanTiltProfileControl) GetTilt() *PanTiltProfileControlAxis {
	if m != nil {
		return m.Tilt
	}
	return nil
}

func (m *PanTiltProfileControl) GetChSpeed() int32 {
	if m != nil {
		return m.ChSpeed
	}
	return 0
}

type LedVarProfileControl struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ColorMap             map[string]int32 `protobuf:"bytes,3,rep,name=colorMap,proto3" json:"colorMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LedVarProfileControl) Reset()         { *m = LedVarProfileControl{} }
func (m *LedVarProfileControl) String() string { return proto.CompactTextString(m) }
func (*LedVarProfileControl) ProtoMessage()    {}
func (*LedVarProfileControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *LedVarProfileControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LedVarProfileControl.Unmarshal(m, b)
}
func (m *LedVarProfileControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LedVarProfileControl.Marshal(b, m, deterministic)
}
func (m *LedVarProfileControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LedVarProfileControl.Merge(m, src)
}
func (m *LedVarProfileControl) XXX_Size() int {
	return xxx_messageInfo_LedVarProfileControl.Size(m)
}
func (m *LedVarProfileControl) XXX_DiscardUnknown() {
	xxx_messageInfo_LedVarProfileControl.DiscardUnknown(m)
}

var xxx_messageInfo_LedVarProfileControl proto.InternalMessageInfo

func (m *LedVarProfileControl) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LedVarProfileControl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LedVarProfileControl) GetColorMap() map[string]int32 {
	if m != nil {
		return m.ColorMap
	}
	return nil
}

type Profile struct {
	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChannelCount int32  `protobuf:"varint,3,opt,name=channelCount,proto3" json:"channelCount,omitempty"`
	// Even though we know this is a GroupProfileControl, it's a little
	// easier on the client side if we keep it the same abstraction.
	Controls             *ProfileControl `protobuf:"bytes,4,opt,name=controls,proto3" json:"controls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetChannelCount() int32 {
	if m != nil {
		return m.ChannelCount
	}
	return 0
}

func (m *Profile) GetControls() *ProfileControl {
	if m != nil {
		return m.Controls
	}
	return nil
}

type ProfilesResponse struct {
	Profiles             map[string]*Profile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProfilesResponse) Reset()         { *m = ProfilesResponse{} }
func (m *ProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*ProfilesResponse) ProtoMessage()    {}
func (*ProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilesResponse.Unmarshal(m, b)
}
func (m *ProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilesResponse.Marshal(b, m, deterministic)
}
func (m *ProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilesResponse.Merge(m, src)
}
func (m *ProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_ProfilesResponse.Size(m)
}
func (m *ProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilesResponse proto.InternalMessageInfo

func (m *ProfilesResponse) GetProfiles() map[string]*Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Void)(nil), "Void")
	proto.RegisterType((*StringMsg)(nil), "StringMsg")
	proto.RegisterType((*ProfileControl)(nil), "ProfileControl")
	proto.RegisterType((*GroupProfileControl)(nil), "GroupProfileControl")
	proto.RegisterType((*EnumProfileControlOption)(nil), "EnumProfileControlOption")
	proto.RegisterType((*EnumProfileControl)(nil), "EnumProfileControl")
	proto.RegisterType((*IntensityProfileControl)(nil), "IntensityProfileControl")
	proto.RegisterType((*PanTiltProfileControlAxis)(nil), "PanTiltProfileControlAxis")
	proto.RegisterType((*PanTiltProfileControl)(nil), "PanTiltProfileControl")
	proto.RegisterType((*LedVarProfileControl)(nil), "LedVarProfileControl")
	proto.RegisterMapType((map[string]int32)(nil), "LedVarProfileControl.ColorMapEntry")
	proto.RegisterType((*Profile)(nil), "Profile")
	proto.RegisterType((*ProfilesResponse)(nil), "ProfilesResponse")
	proto.RegisterMapType((map[string]*Profile)(nil), "ProfilesResponse.ProfilesEntry")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcf, 0x4f, 0x1b, 0x3b,
	0x10, 0xc7, 0xd9, 0xec, 0x6e, 0xc2, 0x0e, 0x0f, 0x1e, 0xcf, 0xfc, 0x78, 0x4b, 0xc4, 0x7b, 0x8d,
	0xdc, 0x0b, 0x55, 0x91, 0x2b, 0x85, 0x0b, 0x2a, 0x87, 0xaa, 0x45, 0x51, 0x8b, 0x04, 0x05, 0x19,
	0x44, 0x0f, 0x3d, 0x99, 0xc4, 0x09, 0x16, 0x1b, 0x7b, 0xe5, 0xdd, 0xa4, 0xe4, 0xc2, 0x3f, 0xd0,
	0x43, 0x6f, 0xfd, 0x47, 0x7a, 0xe9, 0x9f, 0x57, 0xad, 0xd7, 0x9b, 0x1f, 0xdd, 0x80, 0x22, 0xf5,
	0xe6, 0x19, 0x7f, 0xc6, 0xe3, 0xf9, 0xee, 0xcc, 0x1a, 0x02, 0x16, 0x0b, 0x12, 0x6b, 0x95, 0x2a,
	0x5c, 0x05, 0xef, 0x5a, 0x89, 0x0e, 0xfe, 0x0f, 0x82, 0xcb, 0x54, 0x0b, 0xd9, 0x3b, 0x4b, 0x7a,
	0x68, 0x1d, 0xdc, 0x21, 0x8b, 0x42, 0xa7, 0xe1, 0xec, 0x05, 0x34, 0x5b, 0xe2, 0x6f, 0x15, 0x58,
	0xbb, 0xd0, 0xaa, 0x2b, 0x22, 0x7e, 0xac, 0x64, 0xaa, 0x55, 0x84, 0xf6, 0xc1, 0xef, 0x69, 0x35,
	0x88, 0x0d, 0xb6, 0xd2, 0xdc, 0x24, 0xef, 0x33, 0x6b, 0x16, 0xfa, 0xb0, 0x44, 0x73, 0x08, 0xbd,
	0x00, 0x8f, 0xcb, 0x41, 0x3f, 0xac, 0x18, 0x78, 0x83, 0xb4, 0xe4, 0xa0, 0x5f, 0x62, 0x0d, 0x82,
	0x0e, 0x21, 0x10, 0x32, 0xe5, 0x32, 0x11, 0xe9, 0x28, 0x74, 0x0d, 0x1f, 0x92, 0x93, 0xc2, 0x53,
	0x0a, 0x9a, 0xc0, 0xa8, 0x09, 0xb5, 0x98, 0xc9, 0x2b, 0x11, 0xa5, 0xa1, 0x67, 0xe2, 0xb6, 0xc9,
	0x45, 0x6e, 0x97, 0xa2, 0x0a, 0x10, 0xbd, 0x82, 0x6a, 0xc4, 0x3b, 0xd7, 0x4c, 0x87, 0xbe, 0x09,
	0xd9, 0x22, 0xa7, 0xc6, 0x2c, 0x45, 0x58, 0xec, 0x9d, 0x0f, 0x6e, 0x32, 0xb8, 0xc1, 0x5d, 0xd8,
	0x98, 0x53, 0x30, 0x5a, 0x83, 0x8a, 0xe8, 0x58, 0xe5, 0x2a, 0xa2, 0x83, 0x10, 0x78, 0x92, 0xf5,
	0xb9, 0xa9, 0x3b, 0xa0, 0x66, 0x8d, 0x5e, 0xc2, 0x72, 0x3b, 0xc7, 0x93, 0xd0, 0x6d, 0xb8, 0x7b,
	0x2b, 0xcd, 0xbf, 0xc9, 0xec, 0x31, 0x74, 0x0c, 0xe0, 0x07, 0x08, 0xcb, 0x5a, 0x9d, 0xc7, 0xa9,
	0x50, 0x72, 0x7c, 0xb8, 0x33, 0x75, 0xf8, 0x36, 0x54, 0x87, 0x2c, 0x1a, 0xf0, 0x24, 0xac, 0x34,
	0xdc, 0x3d, 0x9f, 0x5a, 0x0b, 0x85, 0x50, 0x1b, 0x32, 0xfd, 0x31, 0xc3, 0x5d, 0x83, 0x17, 0x26,
	0xda, 0x85, 0x60, 0xc8, 0xf4, 0x79, 0xb7, 0x9b, 0xf0, 0x5c, 0x37, 0x9f, 0x4e, 0x1c, 0xf8, 0xab,
	0x03, 0xa8, 0x7c, 0x81, 0x85, 0xea, 0xdc, 0x85, 0xa0, 0x7d, 0xcb, 0xa4, 0xe4, 0xd1, 0xc9, 0xbd,
	0x49, 0xea, 0xd3, 0x89, 0x03, 0x1d, 0x40, 0x4d, 0x99, 0x32, 0x92, 0xd0, 0x33, 0x22, 0xec, 0x90,
	0xc7, 0x0a, 0xa5, 0x05, 0x89, 0x3f, 0xc3, 0xbf, 0x8f, 0x74, 0xc2, 0x9f, 0xdf, 0x08, 0x7f, 0x81,
	0x9d, 0xb9, 0xed, 0xf2, 0xf6, 0x5e, 0x24, 0x99, 0xae, 0x6d, 0xc5, 0x74, 0x92, 0xab, 0xed, 0x53,
	0x6b, 0x65, 0x69, 0xba, 0x42, 0xe6, 0x69, 0x7c, 0x6a, 0xd6, 0x19, 0xdb, 0x17, 0x92, 0xb2, 0x8e,
	0xc9, 0xe1, 0x50, 0x6b, 0x19, 0x3f, 0xbb, 0xcf, 0xfc, 0x9e, 0xf5, 0x1b, 0x0b, 0xff, 0x70, 0x60,
	0x6b, 0x6e, 0xe6, 0x85, 0x8a, 0xda, 0x07, 0x37, 0x66, 0xd2, 0x4e, 0x4a, 0x9d, 0x3c, 0x5a, 0x02,
	0xcd, 0x30, 0x44, 0xc0, 0x4b, 0x27, 0x03, 0xf2, 0x14, 0x6e, 0xb8, 0xac, 0x6f, 0xda, 0xb7, 0x97,
	0x31, 0xe7, 0x1d, 0x33, 0x20, 0x3e, 0x2d, 0x4c, 0xfc, 0xd3, 0x81, 0xcd, 0x79, 0xb3, 0xb2, 0xd0,
	0xa5, 0xdf, 0x64, 0x33, 0x10, 0x29, 0x7d, 0xc6, 0x62, 0x3b, 0x03, 0xcf, 0xe7, 0x0e, 0x1e, 0x39,
	0xb6, 0x54, 0x4b, 0xa6, 0x7a, 0x44, 0xc7, 0x41, 0xf5, 0x23, 0x58, 0x9d, 0xd9, 0xca, 0x7e, 0x5a,
	0x77, 0x7c, 0x54, 0xfc, 0xb4, 0xee, 0xf8, 0x08, 0x6d, 0x82, 0x6f, 0x9a, 0xdf, 0x7e, 0x9b, 0xdc,
	0x78, 0x5d, 0x39, 0x74, 0xf0, 0x03, 0xd4, 0x6c, 0x9a, 0x85, 0x2e, 0x8b, 0xe1, 0x2f, 0xdb, 0x25,
	0xc7, 0x6a, 0x20, 0x53, 0xdb, 0x39, 0x33, 0xbe, 0x99, 0xa1, 0xce, 0xb5, 0x7d, 0x62, 0xa8, 0xbf,
	0x3b, 0xb0, 0x6e, 0x37, 0x13, 0xca, 0x93, 0x58, 0xc9, 0x84, 0xa3, 0x23, 0x58, 0x8e, 0xad, 0x2f,
	0x74, 0x8c, 0x24, 0xcf, 0xc8, 0xef, 0xd0, 0xd8, 0x61, 0xe5, 0x28, 0x02, 0xea, 0x2d, 0x58, 0x9d,
	0xd9, 0x9a, 0x23, 0xc7, 0xff, 0xd3, 0x72, 0xac, 0x34, 0x97, 0x8b, 0xb3, 0xa6, 0x84, 0x69, 0x7e,
	0x02, 0xbf, 0x15, 0x5d, 0x71, 0x8e, 0x1a, 0xe0, 0x5d, 0x08, 0xd9, 0x43, 0x40, 0xc6, 0xcf, 0x42,
	0x7d, 0x6a, 0x8d, 0x97, 0xd0, 0xfe, 0xf8, 0x45, 0x38, 0x15, 0x37, 0x9a, 0xe9, 0x11, 0xf2, 0x49,
	0xf6, 0x94, 0xd4, 0xff, 0x29, 0xdd, 0x1a, 0x2f, 0xdd, 0x54, 0xcd, 0x73, 0x73, 0xf0, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0xcf, 0x1f, 0xc1, 0x7b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ElTeeClient is the client API for ElTee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ElTeeClient interface {
	Ping(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*StringMsg, error)
	ProfileLibrary(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ProfilesResponse, error)
}

type elTeeClient struct {
	cc *grpc.ClientConn
}

func NewElTeeClient(cc *grpc.ClientConn) ElTeeClient {
	return &elTeeClient{cc}
}

func (c *elTeeClient) Ping(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*StringMsg, error) {
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, "/ElTee/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elTeeClient) ProfileLibrary(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ProfilesResponse, error) {
	out := new(ProfilesResponse)
	err := c.cc.Invoke(ctx, "/ElTee/ProfileLibrary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ElTeeServer is the server API for ElTee service.
type ElTeeServer interface {
	Ping(context.Context, *StringMsg) (*StringMsg, error)
	ProfileLibrary(context.Context, *Void) (*ProfilesResponse, error)
}

// UnimplementedElTeeServer can be embedded to have forward compatible implementations.
type UnimplementedElTeeServer struct {
}

func (*UnimplementedElTeeServer) Ping(ctx context.Context, req *StringMsg) (*StringMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedElTeeServer) ProfileLibrary(ctx context.Context, req *Void) (*ProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileLibrary not implemented")
}

func RegisterElTeeServer(s *grpc.Server, srv ElTeeServer) {
	s.RegisterService(&_ElTee_serviceDesc, srv)
}

func _ElTee_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElTeeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ElTee/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElTeeServer).Ping(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ElTee_ProfileLibrary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElTeeServer).ProfileLibrary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ElTee/ProfileLibrary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElTeeServer).ProfileLibrary(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _ElTee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ElTee",
	HandlerType: (*ElTeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ElTee_Ping_Handler,
		},
		{
			MethodName: "ProfileLibrary",
			Handler:    _ElTee_ProfileLibrary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
